print("\t\t\t\t\t\tTrust Fund Buddy")
print("Totals your monthly spending so that your trust your trust fund doesn't run out")
print("<and you're forced to get a real job>\n.")
print("Please enter the requested, monthly costs. Since you're rich, ignore pennies\nand use only dollar amounts.\n")
lam_Tune = input("Lamborghini Tune-Ups: ")
Manhat_Apt = input("Manhattan Apartment: ")
Jet = input("Private Jet Rental: ")
Gift = input("Gifts: ")
Dinn = input("Dinning Out: ")
sta = input("Staff <butlers, chef, driver, assistant>: ")
per = input("Personal Guru and Coach: ")
Com = input("Computer Games: ")
print("")
lam_Tune = int(lam_Tune)
Manhat_Apt = int(Manhat_Apt)
Jet = int(Jet)
Gift = int(Gift)
Dinn = int(Dinn)
sta = int(sta)
per = int(per)
Com = int(Com)
total_pri = lam_Tune + Manhat_Apt + Jet + Gift + Dinn + sta + per + Com
total_pri = str(total_pri)
print("Grand Total: " + total_pri)
